cli_testing:
    autocontinue: true
    chancy_tester: true
    ci:
        active: true
        branch: master
        command: hash dead_hosts_launcher && dead_hosts_launcher --save
        commit_message: '[Autosave][Dead-Hosts::hostsVN-adult-dead-hosts]'
        distribution_branch: master
        end_command: hash dead_hosts_launcher && dead_hosts_launcher --end
        end_commit_message: '[Final/Result][Dead-Hosts::hostsVN-adult-dead-hosts]'
        max_exec_minutes: 20
    cooldown_time: 0.2
    max_workers: 5
dns:
    server:
    - 9.9.9.10
    - 149.112.112.10
lookup:
    collection: false
