cli_testing:
    autocontinue: true
    chancy_tester: true
    ci:
        active: true
        branch: master
        command: hash dead_hosts_launcher && dead_hosts_launcher --save
        commit_message: '[Autosave][Dead-Hosts::hostsVN-adult-dead-hosts]'
        distribution_branch: master
        end_command: hash dead_hosts_launcher && dead_hosts_launcher --end
        end_commit_message: '[Final/Result][Dead-Hosts::hostsVN-adult-dead-hosts]'
        max_exec_minutes: 20
    cooldown_time: 0.2
    display_mode:
        all: true
        dots: true
        execution_time: true
        less: false
    max_workers: 5
dns:
    server:
    - 45.90.28.0
    - 45.90.30.0
lookup:
    collection: false
