cli_testing:
    autocontinue: true
    chancy_tester: true
    ci:
        active: true
        command: hash dead_hosts_launcher && dead_hosts_launcher --save
        commit_message: '[Autosave][Dead-Hosts::hostsVN-adult-dead-hosts]'
        end_command: hash dead_hosts_launcher && dead_hosts_launcher --end
        end_commit_message: '[Final/Result][Dead-Hosts::hostsVN-adult-dead-hosts]'
        max_exec_minutes: 330
    cooldown_time: 0.2
    days_between:
        db_clean: 14
        db_retest: 7
    display_mode:
        all: true
    max_workers: 5
collection:
    push: false
dns:
    server:
    - 9.9.9.10
    - 149.112.112.10
lookup:
    collection: false
proxy:
    global:
        http: null
        https: null
    rules: []
